sudo: required
dist: trusty
language: node_js
node_js:
  - "14"
addons:
  apt:
    packages:
      - git
      - ssh
# define git 公钥 私钥
# ssh scan  cat <<< "$yyy" > xxx
script:
  - npm run build
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa
  - touch ~/.ssh/id_rsa.pub
  - node script/keys.js
  - chmod 600 ~/.ssh/id_rsa
  - chmod 644 ~/.ssh/id_rsa.pub
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - ssh-add ~/.ssh/id_rsa
  - git clone git@github.com:sensibleswap/tokenwallet.git ../tokenwallet
  - mv -v build/* ../tokenwallet/
  - cd ../tokenwallet
  - git add .
  - git commit -m "$TRAVIS_COMMIT"
  - git push origin master
