sudo: required
dist: trusty
language: node_js
node_js:
  - "14"
addons:
  apt:
    packages:
      - git
      - ssh
before_install:
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa
  - touch ~/.ssh/id_rsa.pub
  - cat <<< "$github_private_key" > ~/.ssh/id_rsa
  - cat <<< "$github_public_key" > ~/.ssh/id_rsa.pub
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
# define git 公钥 私钥
# ssh scan
script:
  - npm run build
  - git clone git@github.com:sensibleswap/tokenwallet.git ../tokenwallet
  - mv -v build/* ../tokenwallet/
  - cd ../tokenwallet
  - git add .
  - git commit -m "$TRAVIS_COMMIT"
  - git push origin master
